### ISSUE TITLE
Tap to click is not working

### ISSUE THREAD

**Issue by duongnguyen16** [BluePurplePro/HP-Envy-13-AQ0026TU-Hackintosh#2]
The booting does well!  I appreciate this!
But it have a small issue that tap to click doesn't working. The touchpad move is work, gesture work too but when I click then I have to press the touchpad to make it work.
Any fix? I was trying to create my own EFI but still got this error.
Thanks.

**Comment by BluePurplePro** [comment]
It's not a bug, it's a feature 😂
https://mcmw.abilitynet.org.uk/how-to-make-the-trackpad-easier-to-click-in-macos-13-ventura#enable-tap-to-click
